### ISSUE TITLE
Some apps that are in path aren't recognized

### ISSUE THREAD

**Issue by warpdesign** [dthree/cash#14]
Some external windows commands work (eg. `ipconfig`) while others do not (eg. `grunt`, `code`): is there something that could be done to fix it ?

Right now cash is quite useless if I cannot run grunt :)

**Comment by dthree** [comment]
Yes! Just do a PR and add it to this Array:

https://github.com/dthree/cash/blob/master/commands.json#L32

**Comment by RangerMauve** [comment]
I guess one thing that'd be useful is having cash dynamically look to see if a given command is actually a valid executable in the PATH.

**Comment by dthree** [comment]
The only reason I didn't do that, is that some commands (particularly those that do prompting, etc.) wig out Cash. I'll probably make an exclusions list, and pass everything else through.

**Comment by warpdesign** [comment]
+1 to look for the command in the PATH and have an exclusion list.

@dthree could input be implemented ? (I guess that would require lots of work, just asking ;))

**Comment by dthree** [comment]
> @dthree could input be implemented?

You mean prompts (like the `time` command)? I'm not sure. I have to do more research. See, Cash uses Vorpal for its own control of `stdin` and `stdout`, and when that conflicts with another command, we get funny behavior. But maybe.

**Comment by warpdesign** [comment]
Yes, thats what I meant. I guess I'll check out Vorpal to understand what you mean :)

**Comment by dthree** [comment]
Kk. This is issue a priority fix, btw, and should happen today.

**Comment by dthree** [comment]
Fixed in `v0.3.0`. 

Inverted Windows path paradigm: 

https://github.com/dthree/cash/commit/aa31df0efcd49b9e6ab245b1a2abd9666902c207

In `commands.json`, the `windowsCommands` array is now `windowsExclusions`. By default, all commands will be allowed, unless in `windowsExclusions`. If you find a command that doesn't work with Cash (due to UI writing), please PR it into that array.

If a command is run that isn't in the Windows path, Cash will suppress the default Windows `stderr` and instead return Cash help.
