### ISSUE TITLE
Execute inline command?

### ISSUE THREAD

**Issue by kwonoj** [dthree/cash#55]
Not sure how to describe it, so subject might be incorrect.

Basically what I'm thinking is somewhat like below

```shell
> cash ls
execute ls, then exit to original shell
>

> cash cp src dest
copy...
> 
```

let allow invoke specific command. Is there way without installing as global via`cash-global`?

**Comment by dthree** [comment]
ah. There isn't support for that right now. But we can definitely add it!

**Comment by dthree** [comment]
@nfischer what do you think - if multiple params are passed to `process.argv` in Cash, exit the interactive shell, as opposed to staying in it?

**Comment by nfischer** [comment]
I think the argument should be treated as file names, and then be executed. This is consistent with the behavior of `bash`.

It might be possible to make another utility for this purpose. Over at ShellJS, we started https://github.com/shelljs/shx for this kind of use-case. This could be used like:

```Bash
$ shx ls # use ShellJS's ls command, but right on your command line
$ shx pwd
$ shx grep 'text' file.txt
```

Shx isn't released to npm yet, but you can expect a release in a week or two (once we release ShellJS v0.7). If something similar is a priority for `cash`, I would recommend releasing it as another package, since it lets `cash filename.sh` work very similarly to `bash filename.sh`.

**Comment by dthree** [comment]
I'm probably going to check for a filename, and if a filename is not found, check for a valid cash command, and if that doesn't exist, fall back to the bash file not found error.

**Comment by nfischer** [comment]
That approach raises questions about what to do when multiple parameters are passed. If multiple parameters go to bash, it runs a script with the rest as arguments ($1, $2, etc) to the script.

If someone tries `cash rm ls` what would that do?

**Comment by dthree** [comment]
It would check for `rm` as a bash file. If it finds it, it will pass `ls` in as the first command.

If it doesn't, it will run `rm ls` into the Cash interpreter.

**Comment by nfischer** [comment]
I'm not a fan of this approach, since I'm not aware of any precedent for doing it. I thought that's what the individual packages were meant to solve.

I think it should always execute things as scripts, or if the file can't be found, fail. That's most consistent with bash.

**Comment by dthree** [comment]
Okay fine, no biggie. Closing this issue then.
