### ISSUE TITLE
Add a .cash_profile!

### ISSUE THREAD

**Issue by samkcarlile** [dthree/cash#65]
It would be cool to have something like a .bash_profile for cash! (not sure if this is already implemented. My bad if it exists)

**Comment by samkcarlile** [comment]
Also, I would mark this as an improvement, but it appears I can't add labels unless I am a contributor. Correct me if I'm wrong, I haven't used Github extensively.

**Comment by dthree** [comment]
Hey, welcome to Cash!

---

Cash supports a `.cashrc` (instead of `.bashrc`) file, which is the equivalent of `bash_profile`, except the latter is used for remote logins (like SSH). As Cash is always locally instantiated, it would make more sense to stick with `.cashrc`.

You can put this in your `HOME` directory, and it should work!

**Comment by samkcarlile** [comment]
Ok cool. Thanks a ton, I don't know how I missed that!

**Comment by nfischer** [comment]
> I don't know how I missed that!

That's because I added the docs once I saw this github issue haha. Thanks for pointing it out!

**Comment by dthree** [comment]
:+1:

**Comment by samkcarlile** [comment]
Oh haha thanks! @nfischer
